const $ = id => document.getElementById(id);
const STORAGE = 'geschiedenisTrainerV41';
const MODULES = {
  staatsinrichting: {
    key:'staatsinrichting', label:'Staatsinrichting', icon:'🏛️', bank:Array.isArray(QUESTIONS)?QUESTIONS:[],
    ranks:[
      {min:0,name:'Willem III',icon:'👑'},{min:100,name:'Schoof',icon:'👑'},{min:250,name:'Balkenende',icon:'👑'},
      {min:500,name:'Juliana',icon:'👑'},{min:750,name:'Willem II',icon:'👑'},{min:1000,name:'Colijn',icon:'👑'},
      {min:1500,name:'Balkenende',icon:'👑'},{min:2500,name:'Beatrix',icon:'👑'},{min:5000,name:'Rutte',icon:'👑'},
      {min:7500,name:'Drees',icon:'👑'},{min:10000,name:'Wilhelmina',icon:'👑'}
    ]
  },
  eersteWereldoorlog: {
    key:'eersteWereldoorlog', label:'Eerste Wereldoorlog', icon:'⚔️', bank:Array.isArray(WW1_QUESTIONS)?WW1_QUESTIONS:[],
    ranks:[
      {min:0,name:'Koning van Italië',icon:'👑'},{min:150,name:'Sultan van het Ottomaanse Rijk',icon:'👑'},
      {min:400,name:'President van Frankrijk',icon:'👑'},{min:800,name:'Keizer van Duitsland',icon:'👑'},
      {min:1200,name:'Koning van Groot-Brittannië',icon:'👑'}
    ]
  }
};
let state = JSON.parse(localStorage.getItem(STORAGE)||'null');
if (!state) {
  const old = JSON.parse(localStorage.getItem('geschiedenisTrainerV40')||localStorage.getItem('geschiedenisTrainerV34')||'null');
  state = {unlocked:!!old?.unlocked,studentName:old?.studentName||'',topics:{}};
  if(old) state.topics.staatsinrichting=old;
}
for(const key of Object.keys(MODULES)) if(!state.topics[key]) state.topics[key]=blankTopic();
function blankTopic(){return {score:0,correct:0,wrong:0,streak:0,mastery:{},queue:[],asked:0,daily:{},lastDate:''};}
let activeKey='staatsinrichting', current=null, answered=false, lastQuestionIndex=null;
const norm=s=>String(s??'').toLocaleLowerCase('nl-NL').trim().replace(/\s+/g,' ');
function answerNorm(s){return norm(s).replace(/^[\s.,;:!?]+|[\s.,;:!?]+$/g,'').replace(/^(de|het|een)\s+/,'').replace(/[\s-]+/g,'');}
function answersMatch(given,expected){
  const a=answerNorm(given), b=answerNorm(expected); if(a===b)return true;
  const variants=s=>{const o=new Set([s]); if(s.endsWith('s'))o.add(s.slice(0,-1)); if(s.endsWith('en'))o.add(s.slice(0,-2)); if(s.endsWith('eren'))o.add(s.slice(0,-2)); if(s.endsWith('e'))o.add(s.slice(0,-1)); else o.add(s+'e'); o.add(s+'s');o.add(s+'en');return o};
  for(const x of variants(a))for(const y of variants(b))if(x===y)return true; return false;
}
function topic(){return MODULES[activeKey]}
function ts(){return state.topics[activeKey]}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function displayQuestion(s){s=String(s??'').trim();return s?s[0].toUpperCase()+s.slice(1):s}
function getRank(score){let r=topic().ranks[0];for(const x of topic().ranks)if(score>=x.min)r=x;return r}
function getNextRank(score){return topic().ranks.find(x=>score<x.min)||null}
function progressInfo(score){const r=getRank(score),n=getNextRank(score);if(!n)return {pct:100,text:'Hoogste rang bereikt',next:'Je hebt de hoogste rang bereikt!'};const range=n.min-r.min;return {pct:Math.max(0,Math.min(100,((score-r.min)/range)*100)),text:`${score-r.min} / ${range} punten`,next:`Nog ${n.min-score} punten tot ${n.icon} ${n.name}`}}
function updateRank(){const t=ts(),r=getRank(t.score),p=progressInfo(t.score);for(const [id,val] of [['rankIcon',r.icon],['rankTitle',r.name],['rankScore',`${t.score} punten`],['nextRankText',p.next],['trainerRankIcon',r.icon],['trainerRankTitle',r.name],['trainerRankScore',`${t.score} punten`],['trainerNextRankText',p.next],['trainerRankProgressText',p.text]])if($(id))$(id).textContent=val;for(const id of ['rankBar','trainerRankBar'])if($(id))$(id).style.width=p.pct+'%';}
function updateStats(){const t=ts(),bank=topic().bank,mastered=bank.filter((_,i)=>(t.mastery[i]||0)>=3).length,pct=bank.length?Math.round(mastered/bank.length*100):0;for(const [id,val] of [['score',t.score],['correct',t.correct],['wrong',t.wrong],['streak',t.streak],['wrongHome',t.wrong],['streakHome',t.streak],['masteryPctHome',pct+'%'],['progressTextHome',`${mastered} van ${bank.length} beheerst`],['progressText',`${mastered} van ${bank.length} beheerst`],['progressTextTrainer',`${mastered} van ${bank.length} beheerst`],['masteryPct',pct+'%'],['todayCount',t.daily?.[todayKey()]||0],['conceptOverviewCount',`${mastered} van ${bank.length} beheerst`],['conceptPageCount',`${mastered} van ${bank.length} beheerst`]])if($(id))$(id).textContent=val;for(const id of ['barFillHome','barFill','barFillTrainer','conceptPageBar'])if($(id))$(id).style.width=pct+'%';updateRank();}
function buildQueue(){const t=ts(),bank=topic().bank,w=[];bank.forEach((q,i)=>{const m=Number(t.mastery[i]||0);if(m>=3)return;for(let n=0;n<Math.max(1,4-m);n++)w.push(i)});for(let i=w.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[w[i],w[j]]=[w[j],w[i]]}t.queue=w.slice(0,Math.min(w.length,40));}
function renderConceptOverview(){const list=$('conceptList');if(!list)return;const bank=topic().bank,t=ts();list.innerHTML='';bank.forEach((q,i)=>{const m=Number(t.mastery[i]||0),mastered=m>=3,item=document.createElement('div');item.className='concept-item'+(mastered?' mastered':'');item.dataset.index=i;item.tabIndex=0;item.setAttribute('role','button');item.innerHTML=`<div class="concept-status">${mastered?'✓':'○'}</div><div class="concept-name"><b>${escapeHtml(q.answers[0])}</b><span>${mastered?'Beheerst':`${Math.min(m,3)} / 3 goed`}</span></div><div class="concept-open">›</div>`;list.appendChild(item)});updateStats();}
function openConceptDetail(i){const q=topic().bank[i];if(!q)return;const m=ts().mastery[i]||0;$('conceptDetailTitle').textContent=q.answers.join(' / ');$('conceptDetailShort').textContent=q.question;$('conceptDetailLong').textContent=q.explanation||'Geen extra uitleg beschikbaar.';$('conceptDetailStatus').textContent=m>=3?'✓ Beheerst':`${Math.min(m,3)} / 3 goed`;$('conceptDetail').classList.remove('hidden');}
function closeConceptDetail(){$('conceptDetail').classList.add('hidden')}
function nextQuestion(){const t=ts(),bank=topic().bank;if(!bank.length){$('question').textContent='Er zijn geen vragen geladen.';return}if(!t.queue.length)buildQueue();t.queue=t.queue.filter(i=>(t.mastery[i]||0)<3);if(!t.queue.length){current=null;answered=false;$('questionNo').textContent='Klaar!';$('question').textContent='🎉 Je hebt alle namen en begrippen beheerst!';$('feedback').className='feedback good';$('feedback').textContent='Je kunt via het overzicht een ander onderwerp kiezen.';$('answer').disabled=true;$('checkBtn').classList.add('hidden');$('skipBtn').classList.add('hidden');$('nextBtn').classList.add('hidden');return}if(lastQuestionIndex!==null&&t.queue.length>1&&t.queue[0]===lastQuestionIndex){const a=t.queue.findIndex(i=>i!==lastQuestionIndex);if(a>0)[t.queue[0],t.queue[a]]=[t.queue[a],t.queue[0]]}const idx=t.queue.shift();lastQuestionIndex=idx;current={...bank[idx],idx};answered=false;t.asked++;if(!t.daily)t.daily={};t.daily[todayKey()]=(t.daily[todayKey()]||0)+1;$('questionNo').textContent=`Vraag ${t.asked}`;$('categoryBadge').textContent=topic().label;$('question').textContent=displayQuestion(current.question);$('answer').value='';$('answer').disabled=false;$('checkBtn').disabled=false;$('checkBtn').textContent='Controleer';$('checkBtn').classList.remove('hidden');$('nextBtn').classList.add('hidden');$('feedback').className='feedback';$('feedback').textContent='';save();if(window.matchMedia('(min-width:700px)').matches)$('answer').focus();updateStats();}
function showExtraExplanation(){if(!current)return;$('feedback').className='feedback info';$('feedback').innerHTML=`<div class="feedback-title">💡 Extra uitleg</div><div class="explanation"><b>Uitleg:</b><br>${escapeHtml(current.explanation||'Geen extra uitleg beschikbaar.')}</div>`}
function check(){if(!current||answered)return;const given=$('answer').value;if(!norm(given)){ $('feedback').className='feedback error';$('feedback').textContent='Vul eerst een antwoord in.';return }answered=true;const accepted=[...(current.answers||[]),...(current.alsoGood||[])];const ok=accepted.some(a=>answersMatch(given,a));const t=ts(),oldRank=getRank(t.score);if(ok){t.correct++;t.score+=10;t.streak++;t.mastery[current.idx]=(t.mastery[current.idx]||0)+1;if(t.mastery[current.idx]>=3)t.queue=t.queue.filter(i=>i!==current.idx);$('feedback').className='feedback good';$('feedback').textContent='✓ Goed! +10 punten';$('checkBtn').textContent='Extra uitleg';$('checkBtn').disabled=false}else{t.wrong++;t.score=Math.max(0,t.score-2);t.streak=0;t.mastery[current.idx]=Math.max(0,(t.mastery[current.idx]||0)-1);t.queue.push(current.idx);$('feedback').className='feedback error';$('feedback').innerHTML=`<div class="feedback-title">✗ Nog niet goed</div><div><b>Goed antwoord:</b> ${escapeHtml(current.answers.join(' / '))}</div>${current.alsoGood?.length?`<div><b>Ook goed:</b> ${escapeHtml(current.alsoGood.join(' / '))}</div>`:''}<div class="explanation"><b>Uitleg:</b><br>${escapeHtml(current.explanation||'Geen extra uitleg beschikbaar.')}</div>`}$('answer').disabled=true;$('checkBtn').disabled=!ok;$('nextBtn').classList.remove('hidden');updateStats();renderConceptOverview();save();const nr=getRank(t.score);if(nr.min>oldRank.min){setTimeout(()=>{$('rankUpIcon').textContent=nr.icon;$('rankUpTitle').textContent=nr.name;$('rankUp').classList.remove('hidden')},350)}}
function updateStudentName(){if($('studentNameDisplay'))$('studentNameDisplay').textContent=state.studentName||'leerling'}
const NAME_ALLOWED=/^[\p{L}]+(?: [\p{L}]+)*$/u;const BLOCKED=['fuck','fucking','fucker','shit','bitch','bastard','asshole','dick','piss','cunt','kanker','tering','tyfus','kut','klote','godver','hoer','slet','lul','mongool','nigger','nazi','hitler'];
function validStudentName(name){const v=String(name||'').trim().replace(/\s+/g,' ');if(!v||v.length>40)return{ok:false,message:'Vul een naam in van maximaal 40 tekens.'};if(!NAME_ALLOWED.test(v))return{ok:false,message:'Je naam mag alleen uit letters en spaties bestaan.'};const c=v.toLocaleLowerCase('nl-NL').replace(/[ -]/g,'');if(BLOCKED.some(x=>c.includes(x)))return{ok:false,message:'Deze naam kan niet worden gebruikt. Kies een normale, respectvolle naam.'};return{ok:true,value:v}}
function unlock(){const raw=$('studentName').value.trim(),v=validStudentName(raw);if(!v.ok){$('gateMsg').textContent=v.message;$('gateMsg').className='msg error';return}if(state.unlocked){state.studentName=v.value;save();showApp();return}if(norm($('accessCode').value)===norm(APP_CONFIG.teacherCode)){state.unlocked=true;state.studentName=v.value;save();showApp()}else{$('gateMsg').textContent='De code klopt niet. Vraag je docent om de juiste code.';$('gateMsg').className='msg error'}}
function showApp(){$('gate').classList.add('hidden');$('app').classList.remove('hidden');showHome();updateStudentName();updateStats();}
function showHome(){$('homeScreen').classList.remove('hidden');$('topicScreen').classList.add('hidden');$('trainerScreen').classList.add('hidden');$('conceptScreen').classList.add('hidden');renderTopicChooser();updateStats()}
function renderTopicChooser(){const box=$('topicChooser');if(!box)return;box.innerHTML='';for(const m of Object.values(MODULES)){const t=state.topics[m.key],mastered=m.bank.filter((_,i)=>(t.mastery[i]||0)>=3).length,pct=m.bank.length?Math.round(mastered/m.bank.length*100):0;const el=document.createElement('button');el.className='topic-card card';el.innerHTML=`<div class="topic-icon">${m.icon}</div><div class="topic-main"><div class="eyebrow">ONDERWERP</div><h3>${escapeHtml(m.label)}</h3><p>${m.bank.length} begrippen • ${mastered} beheerst</p><div class="bar"><div style="width:${pct}%"></div></div></div><div class="topic-arrow">›</div>`;el.onclick=()=>selectTopic(m.key);box.appendChild(el)}const future=document.createElement('div');future.className='topic-card card topic-locked';future.innerHTML='<div class="topic-icon">🔒</div><div class="topic-main"><div class="eyebrow">BINNENKORT</div><h3>Nieuwe hoofdstukken</h3><p>Meer examenonderwerpen volgen later.</p></div>';box.appendChild(future)}
function selectTopic(key){activeKey=key;$('homeScreen').classList.add('hidden');$('topicScreen').classList.remove('hidden');$('trainerScreen').classList.add('hidden');$('conceptScreen').classList.add('hidden');setModuleHome();}
function renderTopicHome(){const m=topic(),t=ts(),mastered=m.bank.filter((_,i)=>(t.mastery[i]||0)>=3).length,pct=m.bank.length?Math.round(mastered/m.bank.length*100):0;$('topicTitle').textContent=m.label;$('topicDescription').textContent=m.label==='Staatsinrichting'?'Oefen de begrippen van Staatsinrichting.':'Oefen de begrippen van de Eerste Wereldoorlog.';$('topicEyebrow').textContent=m.label.toUpperCase();$('topicMastery').textContent=pct+'%';$('topicProgressText').textContent=`${mastered} van ${m.bank.length} beheerst`;updateStats();}
function startTraining(){ $('homeScreen').classList.add('hidden');$('conceptScreen').classList.add('hidden');$('trainerScreen').classList.remove('hidden');$('trainerLabel').textContent=topic().label;nextQuestion();}
function resetProgress(){const first=confirm(`Let op: hiermee wordt de voortgang van ${topic().label} gewist. Je naam en toegang blijven behouden.\n\nWil je echt opnieuw beginnen?`);if(!first)return;const second=prompt('Laatste controle: typ OPNIEUW om je voortgang definitief te wissen.');if(second!=='OPNIEUW'){alert('De voortgang is niet gewist.');return}state.topics[activeKey]=blankTopic();save();current=null;answered=false;lastQuestionIndex=null;updateStats();renderTopicChooser();alert('Je voortgang is gewist. Je kunt opnieuw beginnen!')}
$('unlockBtn').onclick=unlock;$('studentName').value=state.studentName||'';$('studentName').onkeydown=e=>{if(e.key==='Enter')$('accessCode').focus()};$('accessCode').onkeydown=e=>{if(e.key==='Enter')unlock()};$('checkBtn').onclick=()=>answered?showExtraExplanation():check();$('nextBtn').onclick=nextQuestion;$('startTrainingBtn').onclick=startTraining;$('conceptOverviewBtn').onclick=()=>{$('homeScreen').classList.add('hidden');$('trainerScreen').classList.add('hidden');$('conceptScreen').classList.remove('hidden');renderConceptOverview()};$('conceptList').onclick=e=>{const i=e.target.closest('.concept-item');if(i)openConceptDetail(Number(i.dataset.index))};$('conceptList').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){const i=e.target.closest('.concept-item');if(i){e.preventDefault();openConceptDetail(Number(i.dataset.index))}}};$('closeConceptDetail').onclick=closeConceptDetail;$('closeConceptDetailBtn').onclick=closeConceptDetail;$('backFromConceptsBtn').onclick=showHome;$('backHomeBtn').onclick=showHome;$('backTopicBtn').onclick=showHome;$('answer').onkeydown=e=>{if(e.key==='Enter')check()};$('skipBtn').onclick=()=>{if(current&&!answered){ts().queue.push(current.idx);save();nextQuestion()}};$('closeRankUp').onclick=()=>$('rankUp').classList.add('hidden');$('teacherBtn').onclick=()=>$('teacherPanel').classList.remove('hidden');$('closeTeacher').onclick=()=>$('teacherPanel').classList.add('hidden');$('resetBtn').onclick=resetProgress;$('resetProgressHomeBtn').onclick=resetProgress;
function setModuleHome(){const m=topic(),t=ts(),mastered=m.bank.filter((_,i)=>(t.mastery[i]||0)>=3).length,pct=m.bank.length?Math.round(mastered/m.bank.length*100):0;$('topicTitle').textContent=m.label;$('topicDescription').textContent=m.label==='Staatsinrichting'?'Oefen de begrippen van Staatsinrichting. Foute vragen komen later opnieuw terug.':'Oefen de begrippen van de Eerste Wereldoorlog. Foute vragen komen later opnieuw terug.';$('topicEyebrow').textContent=m.label.toUpperCase();$('topicMastery').textContent=pct+'%';$('topicProgressText').textContent=`${mastered} van ${m.bank.length} beheerst`;}
$('topicBackBtn').onclick=showHome;
// installatie
let deferredInstallPrompt=null;function isInstalled(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true||document.referrer.startsWith('android-app://')};function setInstallVisibility(){const ins=isInstalled();for(const id of ['installBtn','installHomeCard'])if($(id))$(id).classList.toggle('hidden',ins)}function showInstallFallback(el){if(!el)return;el.classList.remove('hidden');const ua=navigator.userAgent.toLowerCase();el.className='install-instructions';el.innerHTML=/iphone|ipad|ipod/.test(ua)?'<b>iPhone/iPad:</b> tik in Safari op <b>Deel</b> en kies <b>Zet op beginscherm</b>.':/android/.test(ua)?'<b>Android:</b> open het browsermenu <b>⋮</b> en kies <b>App installeren</b> of <b>Toevoegen aan startscherm</b>. Als die optie niet zichtbaar is, open deze site in Chrome.':'<b>Computer:</b> kies het installatie-icoon in de adresbalk of via het browsermenu.'}async function installApp(help){if(deferredInstallPrompt){try{deferredInstallPrompt.prompt();const r=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;if(r.outcome!=='accepted')showInstallFallback(help)}catch(e){showInstallFallback(help)}}else showInstallFallback(help)}window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;setInstallVisibility();});
window.addEventListener('load',()=>setTimeout(setInstallVisibility,500));$('installBtn').onclick=()=>installApp($('installHelp'));$('installHomeBtn').onclick=()=>installApp($('installHomeHelp'));window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;setInstallVisibility()});
setInstallVisibility();updateStudentName();updateStats();renderTopicChooser();if(state.unlocked)showApp();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=41').catch(()=>{});
